name: biblioteca_guiar
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  google_mlkit_text_recognition: ^0.13.0
  firebase_messaging:
  flutter_local_notifications:
  fl_chart: ^0.68.0 # Ou a versÃ£o que vocÃª usa
  vector_math: ^2.1.5 # <--- ADICIONE ISSO AQUI! ðŸ‘ˆ

dependency_overrides:
  vector_math: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
